name: Auto Retrain Pipeline

on:
  schedule:
    - cron: '0 9 * * 1'   # Every Monday at 9AM UTC
  push:
    paths:
      - reports/drift_summary.json
      - trigger_retrain.flag

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[dagsHub]

      - name: Configure DVC remote for DagsHub
        run: |
          dvc remote add -d dagshub_remote https://dagshub.com/${{ secrets.DAGSHUB_USER }}/mlops_1.dvc
          dvc remote modify dagshub_remote auth basic
          dvc remote modify dagshub_remote user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify dagshub_remote password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull latest data and models from DagsHub
        run: dvc pull

      - name: Check drift flag
        id: check_drift
        run: |
          if [ -f "trigger_retrain.flag" ]; then
            echo "Drift detected!"
            echo "run_retrain=true" >> $GITHUB_OUTPUT
          else
            echo "No drift."
            echo "run_retrain=false" >> $GITHUB_OUTPUT
          fi

      - name: Run retraining
        if: steps.check_drift.outputs.run_retrain == 'true'
        run: python src/retraining/retrain_pipeline.py

      - name: Track updated model with DVC
        if: steps.check_drift.outputs.run_retrain == 'true'
        run: |
          dvc add models/model.pkl
          dvc push

      - name: Commit new model metadata and push to GitHub
        if: steps.check_drift.outputs.run_retrain == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add models.dvc .gitignore
          git commit -m "Auto retrain: new model version [skip ci]" || echo "No changes to commit"
          git push
